version: "2.0"
services:

####################################################################################################
####################################################################################################
  _build:
    image: none
    network_mode: bridge
    environment:
      - MAKE
      - MAKEOPT
      - CURVER
      - PKG_RELEASE
      - PROXYSQL_BUILD_TYPE
    command: bash -l -c /opt/entrypoint/entrypoint.bash

####################################################################################################
####################################################################################################
  centos7_build:
    extends:
      service: _build
    image: proxysql/packaging:build-centos7
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/rpmbuild/:/root/rpmbuild/
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/.rpmmacros:/root/.rpmmacros
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=centos7

  centos7_dbg_build:
    extends:
      service: centos7_build
    environment:
      - PKG_RELEASE=dbg-centos7
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
  centos8_build:
    extends:
      service: _build
    image: proxysql/packaging:build-centos8
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/rpmbuild/:/root/rpmbuild/
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/.rpmmacros:/root/.rpmmacros
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=centos8
      - PROXYSQL_BUILD_TYPE=clickhouse

  centos8_clang_build:
    extends:
      service: centos8_build
    image: proxysql/packaging:build-clang-centos8
    environment:
      - PKG_RELEASE=centos8-clang

  centos8_dbg_build:
    extends:
      service: centos8_build
    environment:
      - PKG_RELEASE=dbg-centos8
      - PROXYSQL_BUILD_TYPE=debug


####################################################################################################
  centos9_build:
    extends:
      service: _build
    image: proxysql/packaging:build-centos9
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/rpmbuild/:/root/rpmbuild/
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/.rpmmacros:/root/.rpmmacros
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=centos9
      - PROXYSQL_BUILD_TYPE=clickhouse

  centos9_clang_build:
    extends:
      service: centos9_build
    image: proxysql/packaging:build-clang-centos9
    environment:
      - PKG_RELEASE=centos9-clang

  centos9_dbg_build:
    extends:
      service: centos9_build
    environment:
      - PKG_RELEASE=dbg-centos9
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
####################################################################################################
  fedora38_build:
    extends:
      service: _build
    image: proxysql/packaging:build-fedora38
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/rpmbuild/:/root/rpmbuild/
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/.rpmmacros:/root/.rpmmacros
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=fedora38
      - PROXYSQL_BUILD_TYPE=clickhouse

  fedora38_clang_build:
    extends:
      service: fedora38_build
    image: proxysql/packaging:build-clang-fedora38
    environment:
      - PKG_RELEASE=fedora38-clang

  fedora38_dbg_build:
    extends:
      service: fedora38_build
    environment:
      - PKG_RELEASE=dbg-fedora38
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
  fedora39_build:
    extends:
      service: _build
    image: proxysql/packaging:build-fedora39
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/rpmbuild/:/root/rpmbuild/
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/.rpmmacros:/root/.rpmmacros
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=fedora39
      - PROXYSQL_BUILD_TYPE=clickhouse

  fedora39_clang_build:
    extends:
      service: fedora39_build
    image: proxysql/packaging:build-clang-fedora39
    environment:
      - PKG_RELEASE=fedora39-clang

  fedora39_dbg_build:
    extends:
      service: fedora39_build
    environment:
      - PKG_RELEASE=dbg-fedora39
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
####################################################################################################
  debian10_build:
    extends:
      service: _build
    image: proxysql/packaging:build-debian10
    volumes:
      - ./docker/images/proxysql/deb-compliant/latest-package/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=debian10
      - PROXYSQL_BUILD_TYPE=clickhouse

  debian10_dbg_build:
    extends:
      service: debian10_build
    environment:
      - PKG_RELEASE=dbg-debian10
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
  debian11_build:
    extends:
      service: _build
    image: proxysql/packaging:build-debian11
    volumes:
      - ./docker/images/proxysql/deb-compliant/latest-package/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=debian11
      - PROXYSQL_BUILD_TYPE=clickhouse

  debian11_clang_build:
    extends:
      service: debian11_build
    image: proxysql/packaging:build-clang-debian11
    environment:
      - PKG_RELEASE=debian11-clang

  debian11_dbg_build:
    extends:
      service: debian11_build
    environment:
      - PKG_RELEASE=dbg-debian11
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
  debian12_build:
    extends:
      service: _build
    image: proxysql/packaging:build-debian12
    volumes:
      - ./docker/images/proxysql/deb-compliant/latest-package/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=debian12
      - PROXYSQL_BUILD_TYPE=clickhouse

  debian12_clang_build:
    extends:
      service: debian12_build
    image: proxysql/packaging:build-clang-debian12
    environment:
      - PKG_RELEASE=debian12-clang

  debian12_dbg_build:
    extends:
      service: debian12_build
    environment:
      - PKG_RELEASE=dbg-debian12
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
####################################################################################################
  ubuntu16_build:
    extends:
      service: _build
    image: proxysql/packaging:build-ubuntu16
    volumes:
      - ./docker/images/proxysql/deb-compliant/pre-systemd/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=ubuntu16

  ubuntu16_dbg_build:
    extends:
      service: ubuntu16_build
    environment:
      - PKG_RELEASE=dbg-ubuntu16
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
  ubuntu18_build:
    extends:
      service: _build
    image: proxysql/packaging:build-ubuntu18
    volumes:
      - ./docker/images/proxysql/deb-compliant/latest-package/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=ubuntu18
      - PROXYSQL_BUILD_TYPE=clickhouse

  ubuntu18_dbg_build:
    extends:
      service: ubuntu18_build
    environment:
      - PKG_RELEASE=dbg-ubuntu18
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
  ubuntu20_build:
    extends:
      service: _build
    image: proxysql/packaging:build-ubuntu20
    volumes:
      - ./docker/images/proxysql/deb-compliant/latest-package/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=ubuntu20
      - PROXYSQL_BUILD_TYPE=clickhouse

  ubuntu20_clang_build:
    extends:
      service: ubuntu20_build
    image: proxysql/packaging:build-clang-ubuntu20
    environment:
      - PKG_RELEASE=ubuntu20-clang

  ubuntu20_dbg_build:
    extends:
      service: ubuntu20_build
    environment:
      - PKG_RELEASE=dbg-ubuntu20
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
  ubuntu22_build:
    extends:
      service: _build
    image: proxysql/packaging:build-ubuntu22
    volumes:
      - ./docker/images/proxysql/deb-compliant/latest-package/ctl/:/root/ctl/
      - ./docker/images/proxysql/deb-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=ubuntu22
      - PROXYSQL_BUILD_TYPE=clickhouse

  ubuntu22_clang_build:
    extends:
      service: ubuntu22_build
    image: proxysql/packaging:build-clang-ubuntu22
    environment:
      - PKG_RELEASE=ubuntu22-clang

  ubuntu22_dbg_build:
    extends:
      service: ubuntu22_build
    environment:
      - PKG_RELEASE=dbg-ubuntu22
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
####################################################################################################
  opensuse15_build:
    extends:
      service: _build
    image: proxysql/packaging:build-opensuse15
    volumes:
      - ./docker/images/proxysql/suse-compliant/rpmmacros/rpmbuild/:/root/rpmbuild/
      - ./docker/images/proxysql/suse-compliant/rpmmacros/.rpmmacros:/root/.rpmmacros
      - ./docker/images/proxysql/suse-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=opensuse15
      - PROXYSQL_BUILD_TYPE=clickhouse

  opensuse15_clang_build:
    extends:
      service: opensuse15_build
    image: proxysql/packaging:build-clang-opensuse15
    environment:
      - PKG_RELEASE=opensuse15-clang

  opensuse15_dbg_build:
    extends:
      service: opensuse15_build
    environment:
      - PKG_RELEASE=dbg-opensuse15
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
####################################################################################################
  almalinux8_build:
    extends:
      service: _build
    image: proxysql/packaging:build-almalinux8
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/rpmbuild/:/root/rpmbuild/
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/.rpmmacros:/root/.rpmmacros
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=almalinux8
      - PROXYSQL_BUILD_TYPE=clickhouse

  almalinux8_clang_build:
    extends:
      service: almalinux8_build
    image: proxysql/packaging:build-clang-almalinux8
    environment:
      - PKG_RELEASE=almalinux8-clang

  almalinux8_dbg_build:
    extends:
      service: almalinux8_build
    environment:
      - PKG_RELEASE=dbg-almalinux8
      - PROXYSQL_BUILD_TYPE=debug

####################################################################################################
  almalinux9_build:
    extends:
      service: _build
    image: proxysql/packaging:build-almalinux9
    volumes:
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/rpmbuild/:/root/rpmbuild/
      - ./docker/images/proxysql/rhel-compliant/rpmmacros/.rpmmacros:/root/.rpmmacros
      - ./docker/images/proxysql/rhel-compliant/entrypoint/:/opt/entrypoint/
      - ./:/opt/proxysql/
    environment:
      - PKG_RELEASE=almalinux9
      - PROXYSQL_BUILD_TYPE=clickhouse

  almalinux9_clang_build:
    extends:
      service: almalinux9_build
    image: proxysql/packaging:build-clang-almalinux9
    environment:
      - PKG_RELEASE=almalinux9-clang

  almalinux9_dbg_build:
    extends:
      service: almalinux9_build
    environment:
      - PKG_RELEASE=dbg-almalinux9
      - PROXYSQL_BUILD_TYPE=debug


####################################################################################################
####################################################################################################
