name: CI-repltests

on:
  workflow_dispatch:
  workflow_call:

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref_name }}
#  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        testdist: [ 'ubuntu22' ]
#        infradb: [ 'mysql57', 'mysql80', 'mysql81', 'mysql82', 'mariadb10', 'mariadb11' ]
        infradb: [ 'mysql57' ]
    env:
      TESTDIST: ${{ matrix.testdist }}
      INFRADB:  ${{ matrix.infradb }}
      BLDCACHE: CI-builds_${{ github.sha }}_${{ matrix.testdist }}-tap_src
#      BASELINE: ${{ vars[format('BASELINE_3P_MARIADB_CONNECTOR_C_{0}', matrix.infradb)] }}

    steps:
    
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y sysbench gettext
      
    - name: Cache restore src
      id: cache-src
      uses: actions/cache/restore@v4
      with:
        key: CI-builds_${{ github.sha }}_ubuntu22-tap_src
        fail-on-cache-miss: true
        path: |
          proxysql/src/

    - name: Checkout jenkins_build_scripts
      uses: actions/checkout@v4
      with:
        repository: 'proxysql/jenkins-build-scripts'
        ref: 'proxysql_repl_tests'
        fetch-depth: 0
        path: 'jenkins-build-scripts'
        token: ${{ secrets.GH_TOKEN }}

    - name: Docker-hoster
      run: |
        cd jenkins-build-scripts/infra-docker-hoster
        docker-compose up -d

    - name: Replication-tests
      run: |
        set +e
        
        cd jenkins-build-scripts
        sed -i "s|#!/usr/bin/bash|#!/usr/bin/bash +e|" proxysql_repl_tests/bin/debezium-check.bash
        sed -i "s|#!/usr/bin/bash|#!/usr/bin/bash +e|" proxysql_repl_tests/exec_repl_test.sh
        sed -i "s|JENKINS_SCRIPTS_PATH=.*|JENKINS_SCRIPTS_PATH=${{ github.workspace }}/jenkins-build-scripts|" env.sh
        sed -i "s|WORKSPACE=.*|WORKSPACE=${{ github.workspace }}/proxysql|" env.sh
        
        cd proxysql_repl_tests
        #./exec_repl_test.sh 5.7 no-ssl debezium
        RCS=0
        for N in {1..1}; do
          ./exec_all_repl_tests.sh
          RC=$?
          RCS=$(( $RCS + $RC ))
        done
        
        #./docker-compose-destroy.bash
        sudo chmod -R 777 ${{ github.workspace }}/*
        exit $RCS
        
    - name: Archive artifacts logs
      if: ${{ failure() && !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}-${{ github.sha }}-logs-run#${{ github.run_number }}
        path: |
          proxysql/ci_*_logs/
          
    - name: Archive artifacts bin
      if: ${{ failure() && !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}-${{ github.sha }}-bin-run#${{ github.run_number }}
        path: |
          proxysql/binaries/
          proxysql/src/
          proxysql/libs/
#          proxysql/deps/
          
          
